[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
size = 10.5

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
import = ["~/.config/alacritty/colorschemes/kanagawa.toml"]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
